# Generated by Django 4.0.2 on 2022-02-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productcolour_productsize_alter_product_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productcolour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productsize',
        ),
    ]
